export default [
  {
    id:"1",
    user:{
      username:"mredon0",
      profilePhotoUrl:"https://robohash.org/consequunturipsumut.png?size=50x50&set=set1",
    },
    postedAt: "5/5/2020",
    post:"nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla",
    photoUrl:"http://dummyimage.com/140x186.jpg/cc0000/ffffff",
    like:"100",
    comment:"123",
  },
  {
    id:"2",
    user:{
      username:"umortlock1",
      profilePhotoUrl:"https://robohash.org/distinctioquoset.png?size=50x50&set=set1",
    },
    postedAt: "3/13/2020",
    post:"nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla",
    photoUrl:"http://dummyimage.com/129x100.png/ff4444/ffffff",
    like:"100",
    comment:"123",
  },
  {
    id:"3",
    user:{
      username:"umortlock1",
      profilePhotoUrl:"https://robohash.org/distinctioquoset.png?size=50x50&set=set1",
    },
    postedAt: "3/13/2020",
    post:"nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla",
    photoUrl:"http://dummyimage.com/129x100.png/ff4444/ffffff",
    like:"100",
    comment:"123",
  },
  {
    id:"4",
    user:{
      username:"umortlock1",
      profilePhotoUrl:"https://robohash.org/distinctioquoset.png?size=50x50&set=set1",
    },
    postedAt: "3/13/2020",
    post:"nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla",
    photoUrl:"http://dummyimage.com/129x100.png/ff4444/ffffff",
    like:"100",
    comment:"123",
  },
  {
    id:"5",
    user:{
      username:"umortlock1",
      profilePhotoUrl:"https://robohash.org/distinctioquoset.png?size=50x50&set=set1",
    },
    postedAt: "3/13/2020",
    post:"nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla",
    photoUrl:"http://dummyimage.com/129x100.png/ff4444/ffffff",
    like:"100",
    comment:"123",
  },
  {
    id:"6",
    user:{
      username:"umortlock1",
      profilePhotoUrl:"https://robohash.org/distinctioquoset.png?size=50x50&set=set1",
    },
    postedAt: "3/13/2020",
    post:"nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla",
    photoUrl:"http://dummyimage.com/129x100.png/ff4444/ffffff",
    like:"100",
    comment:"123",
  },
  {
    id:"7",
    user:{
      username:"umortlock1",
      profilePhotoUrl:"https://robohash.org/distinctioquoset.png?size=50x50&set=set1",
    },
    postedAt: "3/13/2020",
    post:"nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla",
    photoUrl:"http://dummyimage.com/129x100.png/ff4444/ffffff",
    like:"100",
    comment:"123",
  },
  {
    id:"8",
    user:{
      username:"umortlock1",
      profilePhotoUrl:"https://robohash.org/distinctioquoset.png?size=50x50&set=set1",
    },
    postedAt: "3/13/2020",
    post:"nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla",
    photoUrl:"http://dummyimage.com/129x100.png/ff4444/ffffff",
    like:"100",
    comment:"123",
  },
  {
    id:"9",
    user:{
      username:"umortlock1",
      profilePhotoUrl:"https://robohash.org/distinctioquoset.png?size=50x50&set=set1",
    },
    postedAt: "3/13/2020",
    post:"nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla",
    photoUrl:"http://dummyimage.com/129x100.png/ff4444/ffffff",
    like:"100",
    comment:"123",
  },

]
